---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "TF_key"
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ec2.access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2.secret_key}}"  # From vault as defined
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-04a81a99f5ec58529", name: "manage-node-1-ubuntu" } # Update AMI ID according
      - { image: "ami-0ae8f15ae66fe8cda", name: "manage-node-2" } # to your account
      - { image: "ami-0ae8f15ae66fe8cda", name: "manage-node-3" }